// English Comment: Folder Tree Structure representation with Guideline folder and comprehensive IT subfolders.
final Map<String, List<String>> folderStructure = {
  'Guideline': [],
  'IT': [
    'Artificial Intelligence',
    'C Programming',
    'Data Communication',
    'Database Management System',
    'Digital Electronics',
    'Object Oriented Programming',
    'Operating System',
    'Software Engineering',
    'Computer Fundamentals',
    'Data Structure & Algorithm',
    'Computer Networking',
    'Computer Architecture & Microprocessor',
    'Discrete Mathematics',
    'Cyber Security',
    'Compiler Design',
    'Internet of Things (IoT)',
    'Data Center',
    'Circuit Analysis',
    'ICT in Banking Sector',
  ],
  'BANGLA': ['Literature', 'Grammar'],
  'ENGLISH': ['Literature', 'Grammar'],
  'GENERAL KNOWLEDGE': ['Bangladesh', 'International'],
  'MATHEMATICS': [],
  'ANALYTICAL ANALYSIS': [],
  'FOCUS WRITING': [],
  'PREVIOUS YEAR QUESTIONS': ['General', 'IT'],
};